# Generated by Django 4.1.4 on 2022-12-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='counter', to='inventory.user')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='date_recorded', to='inventory.datetable')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_name', to='inventory.consumable')),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='item_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stored', to='inventory.location'),
        ),
    ]
